# This is a basic workflow to help you get started with Actions

name: GitHub Actions For Deploy GitHub pages

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
    
      - name: Install and Build
        run: |
          npm install
          npm run build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with: 
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}
